# {County, Muni, Year, Month} aggregation

- Group crashes by {County, Muni, Year, Month}
- Compute sums of {fatal,injury,property} x {victims,crashes}
- Save SQLite (in `www` dir, for use by dev web server)
- Upload to S3 (`s3://nj-crashes/njdot/data/cmymc.db`)

In [1]:
from utz import *
from njdot import crashes, vehicles, occupants, pedestrians
from njdot.paths import CMYMC_DB
from nj_crashes.utils import sql

In [2]:
%%time
c = crashes.load(cols=['dt', 'year', 'cc', 'mc', 'severity', 'tk', 'ti', 'pk', 'pi', ])
y = c.year.rename('y')
m = c.dt.dt.month.rename('m')
c = sxs(y, m, c[[k for k in c if k not in ['y', 'm', 'year', 'dt']]])
c

Reading /Users/ryan/c/hccs/crashes/njdot/data/crashes.parquet

CPU times: user 295 ms, sys: 132 ms, total: 427 ms
Wall time: 258 ms

            y   m  cc      mc severity  tk  ti  pk  pi
id
0        2001  12   1     1.0        p   0   0   0   0
1        2001   1   1     1.0        p   0   0   0   0
2        2001   4   1     1.0        i   0   4   0   0
3        2001   4   1     1.0        i   0   1   0   0
4        2001   4   1     1.0        p   0   0   0   0
...       ...  ..  ..     ...      ...  ..  ..  ..  ..
6567545  2023   8  99  9901.0        i   0   1   0   0
6567546  2023   2  99  9902.0        p   0   0   0   0
6567547  2023   4  99  9902.0        i   0   1   0   0
6567548  2023   7  99  9902.0        p   0   0   0   0
6567549  2023  11  99  9902.0        p   0   0   0   0

[6567550 rows x 9 columns]

In [3]:
cmym_cols = [ 'cc', 'mc', 'y', 'm', ]
cmymtc_cols = cmym_cols + [ 'condition', 'type', ]

In [4]:
p = pedestrians.load()
p

Reading /Users/ryan/c/hccs/crashes/njdot/data/pedestrians.parquet

,crash_id,pn,condition,city,state,zip,dob,age,sex,alc_test_given,alc_test_type,alc_test_results,charge1,summons1,traffic_controls,cir1,cir2,dir,act,inj_loc,inj_type,med_refused,safety_used,hospital,status1,cyclist,other,charge2,summons2,charge3,summons3,charge4,summons4,status2
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,7,1,3,ABSECON,NJ,08201,07/28/1990,10,M,,,,,,<NA>,<NA>,<NA>,<NA>,41,1,5,<NA>,<NA>,,1,False,False,,,,,,,<NA>
1,48,1,3,ABSECON,NJ,08201,01/16/1967,34,M,,,,,,<NA>,<NA>,<NA>,<NA>,<NA>,1,4,<NA>,<NA>,,<NA>,True,False,,,,,,,<NA>
2,76,1,2,EGG HARBOR TWP.,NJ,08234,11/16/1952,48,F,N,,,,,<NA>,<NA>,<NA>,<NA>,46,12,3,<NA>,<NA>,,1,False,False,,,,,,,<NA>
3,114,1,4,GALLOWAY TWP.,NJ,08205,03/31/1959,42,F,N,,,SUBPOENA,,<NA>,<NA>,<NA>,<NA>,49,7,<NA>,<NA>,<NA>,,1,False,False,,,,,,,<NA>
4,236,1,4,ABSECON,NJ,08201,04/18/1953,48,M,N,,,,,<NA>,<NA>,<NA>,<NA>,43,1,4,<NA>,<NA>,,1,False,False,,,,,,,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193104,6567164,1,4,WASHINGTON,NJ,07882,None,68,M,N,,,,,3,85,85,3,43,10,8,2,<NA>,,1,False,False,,,,,,,<NA>
193105,6567210,1,2,WASHINGTON,NJ,07882,None,16,M,N,,,,,4,77,73,4,34,8,8,2,<NA>,5404,1,False,False,,,,,,,<NA>
193106,6567227,1,4,WASHINGTON,NJ,07882,None,61,M,N,,,,,<NA>,85,<NA>,<NA>,43,11,8,2,<NA>,7101,1,False,False,,,,,,,<NA>
193107,6567364,1,4,PHILLIPSBURG,NJ,08865,None,31,M,N,,,,,<NA>,89,73,<NA>,42,11,8,1,1,,1,False,False,,,,,,,<NA>
193108,6567484,1,2,BLAIRSTOWN,NJ,07825,None,31,,,,,,,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,,<NA>,True,False,,,,,,,<NA>

In [5]:
pm = p.merge(c, left_on='crash_id', right_index=True, how='left', validate='m:1')
pm = pm[(pm.condition >= 1) & (pm.condition <= 5)]
pm.loc[ pm.cyclist, 'type'] = 'b'
pm.loc[~pm.cyclist, 'type'] = 't'
pg = pm.groupby(cmymtc_cols).size().rename('num')
pg

cc  mc    y     m   condition  type
1   1.0   2001  1   4          t       1
                6   3          t       1
                    4          t       1
                7   4          b       1
                9   3          b       1
                                      ..
21  23.0  2016  4   1          b       1
          2017  8   4          b       1
          2019  7   2          b       1
          2020  12  1          t       1
          2023  7   2          b       1
Name: num, Length: 87691, dtype: int64

In [6]:
o = occupants.load()
o

Reading /Users/ryan/c/hccs/crashes/njdot/data/occupants.parquet

,crash_id,vehicle_id,on,condition,pos,eject,age,sex,inj_loc,inj_type,med_refused,safety_avail,safety_used,airbag,hospital
id,,,,,,,,,,,,,,,
0,0,0,1,<NA>,1,1,38,M,<NA>,<NA>,,4,4,<NA>,
1,0,1,1,<NA>,1,1,63,F,<NA>,<NA>,,4,4,<NA>,
2,1,2,1,<NA>,<NA>,<NA>,<NA>,,<NA>,<NA>,,<NA>,<NA>,<NA>,
3,2,4,1,3,1,1,29,F,6,8,,4,4,<NA>,
4,2,4,2,3,3,1,7,M,8,5,,4,4,<NA>,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14905985,6567541,12375687,1,5,1,1,27,F,<NA>,<NA>,,4,4,6,
14905986,6567542,12375688,1,5,1,1,30,M,<NA>,<NA>,,4,4,4,
14905987,6567542,12375689,2,5,3,1,32,M,<NA>,<NA>,,4,4,4,
14905988,6567543,12375690,1,5,1,1,74,M,<NA>,<NA>,,4,4,4,
14905989,6567543,12375690,1,3,1,1,54,F,8,4,02,4,4,4,7102

In [7]:
om = o.merge(c, left_on='crash_id', right_index=True, how='left', validate='m:1')
om = om[(om.condition >= 1) & (om.condition <= 5)]
om['type'] = nan
om.loc[om.pos == 1, 'type'] = 'd'
om.loc[om.pos > 1, 'type'] = 'o'
om = om[~om.type.isna()]
og = om.groupby(cmymtc_cols).size().rename('num')
og

/var/folders/fn/ym_dc2bd6_904g_tzgp6_wxc0000gn/T/ipykernel_14293/3748009522.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'd' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  om.loc[om.pos == 1, 'type'] = 'd'

cc  mc    y     m   condition  type
1   1.0   2001  1   3          d        3
                    4          d        6
                               o        4
                2   2          d        1
                    4          d        6
                                       ..
21  23.0  2023  11  5          d       20
                               o        4
                12  3          d        2
                    5          d       16
                               o        4
Name: num, Length: 402634, dtype: int64

In [8]:
g = pd.concat([ pg, og ]).sort_index()
g

cc  mc    y     m   condition  type
1   1.0   2001  1   3          d        3
                    4          d        6
                               o        4
                               t        1
                2   2          d        1
                                       ..
21  23.0  2023  11  5          d       20
                               o        4
                12  3          d        2
                    5          d       16
                               o        4
Name: num, Length: 490325, dtype: int64

In [9]:
occ_severity = om.groupby('crash_id')['condition'].min().rename('occ_severity')
ped_severity = pm.groupby('crash_id')['condition'].min().rename('ped_severity')
sev = sxs(occ_severity, ped_severity).min(axis=1).rename('condition')
cs = sxs(c.drop(columns='severity'), sev)
cs['condition'] = cs.condition.fillna(5)
cs

            y   m  cc      mc  tk  ti  pk  pi  condition
0        2001  12   1     1.0   0   0   0   0          5
1        2001   1   1     1.0   0   0   0   0          5
2        2001   4   1     1.0   0   4   0   0          3
3        2001   4   1     1.0   0   1   0   0          4
4        2001   4   1     1.0   0   0   0   0          5
...       ...  ..  ..     ...  ..  ..  ..  ..        ...
6567545  2023   8  99  9901.0   0   1   0   0          5
6567546  2023   2  99  9902.0   0   0   0   0          5
6567547  2023   4  99  9902.0   0   1   0   0          5
6567548  2023   7  99  9902.0   0   0   0   0          5
6567549  2023  11  99  9902.0   0   0   0   0          5

[6567550 rows x 9 columns]

In [10]:
cxs = cs.groupby(cmym_cols + ['condition']).size().rename('num_crashes')
cxs

cc  mc      y     m   condition
1   1.0     2001  1   3             2
                      4             8
                      5            10
                  2   2             1
                      4             5
                                   ..
99  9901.0  2023  12  5             1
    9902.0  2023  2   5             1
                  4   5             1
                  7   5             1
                  11  5             1
Name: num_crashes, Length: 388671, dtype: int64

In [11]:
cmymc = g.reset_index(level=5).pivot(columns='type', values='num')[['d', 'o', 't', 'b']].rename(columns={
    'd': 'drivers',
    'o': 'passengers',
    't': 'pedestrians',
    'b': 'cyclists',
})
cmymc = sxs(cmymc, cxs).fillna(0).astype(int)
cmymc

                             drivers  passengers  pedestrians  cyclists  \
cc mc     y    m  condition
1  1.0    2001 1  3                3           0            0         0
                  4                6           4            1         0
               2  2                1           0            0         0
                  4                6           2            0         0
               3  3                2           1            0         0
...                              ...         ...          ...       ...
99 9901.0 2023 12 5                0           0            0         0
   9902.0 2023 2  5                0           0            0         0
               4  5                0           0            0         0
               7  5                0           0            0         0
               11 5                0           0            0         0

                             num_crashes
cc mc     y    m  condition
1  1.0    2001 1  3                    2
                  4                    8
               2  2                    1
                  4                    5
               3  3                    2
...                                  ...
99 9901.0 2023 12 5                    1
   9902.0 2023 2  5                    1
               4  5                    1
               7  5                    1
               11 5                    1

[392776 rows x 5 columns]

In [12]:
hc = cmymc.loc[9].reset_index()
hcf = hc[hc.condition == 1]
hcf

,mc,y,m,condition,drivers,passengers,pedestrians,cyclists,num_crashes
6,1.0,2001,3,1,2,0,0,0,2
16,1.0,2001,7,1,2,0,0,0,2
32,1.0,2001,12,1,1,0,0,0,1
74,1.0,2003,5,1,0,0,1,0,1
130,1.0,2005,1,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...
7751,12.0,2019,6,1,0,1,0,0,1
7825,12.0,2021,5,1,0,0,1,0,1
7844,12.0,2021,10,1,0,0,1,0,1
7851,12.0,2021,12,1,0,0,0,1,1
7919,12.0,2023,9,1,0,0,1,0,1

In [13]:
hcf.sum()

mc               2798.0
y              861133.0
m                2800.0
condition         428.0
drivers           217.0
passengers         83.0
pedestrians       219.0
cyclists           22.0
num_crashes       513.0
dtype: Float64

In [14]:
%%time
sql.write(
    cmymc, 'cmymc', CMYMC_DB,
    idxs=[('cc', 'mc', 'y', 'm', 'condition')],
    rm=True,
    page_size=2**16,
)

Removing /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db
Writing 392776 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cmymc)
Wrote DB: 32120832 bytes
After indices: 39514112 bytes

CPU times: user 3.27 s, sys: 217 ms, total: 3.49 s
Wall time: 3.66 s

After setting page_size=65536 and vacuum: 37486592 bytes

In [15]:
def sum_idx_col(df0, col, tbl_suffix='', page_size=None):
    idx_cols0 = df0.index.names
    idx_cols1 = [ c for c in idx_cols0 if c != col ]
    assert len(idx_cols1) + 1 == len(idx_cols0)
    df1 = df0.reset_index().drop(columns=col).groupby(idx_cols1).sum()
    tbl = ''.join([ c[0] for c in idx_cols1 ]) + tbl_suffix
    sql.write(
        df1, tbl, CMYMC_DB,
        idxs=[tuple(idx_cols1)],
        replace=False,
        page_size=page_size,
    )
    return df1

In [16]:
cmyc = sum_idx_col(cmymc, 'm')
cmyc

Writing 51430 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cmyc)
Wrote DB: 41353216 bytes
After indices: 42270720 bytes

                          drivers  passengers  pedestrians  cyclists  \
cc mc     y    condition
1  1.0    2001 1                1           1            0         0
               2                4           4            1         0
               3               26           8            1         1
               4               90          53            3         1
               5                0           0            0         0
...                           ...         ...          ...       ...
21 23.0   2023 3               13           1            0         0
               4               12           6            0         0
               5              144          36            0         0
99 9901.0 2023 5                0           0            0         0
   9902.0 2023 5                0           0            0         0

                          num_crashes
cc mc     y    condition
1  1.0    2001 1                    2
               2                    5
               3                   27
               4                   94
               5                  184
...                               ...
21 23.0   2023 3                   11
               4                   11
               5                  111
99 9901.0 2023 5                    2
   9902.0 2023 5                    4

[51430 rows x 5 columns]

In [17]:
cymc = sum_idx_col(cmymc, 'mc')
cymc

Writing 27774 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cymc)
Wrote DB: 44367872 bytes
After indices: 44892160 bytes

                      drivers  passengers  pedestrians  cyclists  num_crashes
cc y    m  condition
1  2001 1  1                0           0            2         0            2
           2               10           5            3         0           12
           3               44          17            4         1           55
           4              155          86            9         5          164
           5                0           0            0         0          496
...                       ...         ...          ...       ...          ...
99 2023 4  5                0           0            0         0            1
        7  5                0           0            0         0            1
        8  5                0           0            0         0            1
        11 5                0           0            0         0            1
        12 5                0           0            0         0            1

[27774 rows x 5 columns]

In [18]:
ymc = sum_idx_col(cymc, 'cc')
ymc

Writing 1380 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (ymc)
Wrote DB: 45154304 bytes
After indices: 45219840 bytes

                   drivers  passengers  pedestrians  cyclists  num_crashes
y    m  condition
2001 1  1               24           9            8         1           41
        2              144          50           34         2          182
        3             1048         390          150        20         1262
        4             5121        2129          336        37         5187
        5                0           0            0         0        22225
...                    ...         ...          ...       ...          ...
2023 12 1               22           8           21         2           50
        2              120          53           54        11          205
        3             1419         484          153        61         1601
        4             2242         772          174        37         2287
        5            24736        8059           20        27        19003

[1380 rows x 5 columns]

In [19]:
cyc = sum_idx_col(cymc, 'm')
cyc

Writing 2412 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cyc)
Wrote DB: 45481984 bytes
After indices: 45547520 bytes

                   drivers  passengers  pedestrians  cyclists  num_crashes
cc y    condition
1  2001 1               38          14           14         5           65
        2              119          48           28         8          158
        3              617         274           72        47          756
        4             1982        1157           93        70         2121
        5                0           0            0         0         6639
...                    ...         ...          ...       ...          ...
21 2023 2               15           3            1         1           16
        3              124          38            3         1          133
        4              197          45            3         3          178
        5             1502         434            0         0         1526
99 2023 5                0           0            0         0            6

[2412 rows x 5 columns]

In [20]:
yc = sum_idx_col(cyc, 'cc')
yc

Writing 115 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (yc)
Wrote DB: 45744128 bytes
After indices: 45809664 bytes

                drivers  passengers  pedestrians  cyclists  num_crashes
y    condition
2001 1              418         158          118        23          662
     2             1899         661          427       124         2595
     3            13972        5609         1931       958        17718
     4            58388       27542         3514      1384        60004
     5                0           0            0         0       231717
...                 ...         ...          ...       ...          ...
2023 1              288          62          175        21          523
     2             1681         555          517       197         2466
     3            14522        4752         1251       839        16109
     4            24226        8559         1495       712        24511
     5           226028       75999          200       242       204088

[115 rows x 5 columns]

In [21]:
v = vehicles.load()
v

Reading /Users/ryan/c/hccs/crashes/njdot/data/vehicles.parquet

,crash_id,vn,ins_co,owner_state,make,model,color,vy,state,rm_by,impact_loc,damage_loc,type,use,cargo_type,cir1,cir2,dir,act,ev1,ev2,ev3,ev4,oversize,hit_run,departure,damage,ev
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,1,426,NJ,NISSAN MAXIMA,,BUR,1991,NJ,<NA>,8,7,1,,<NA>,25,<NA>,1,3,26,<NA>,<NA>,<NA>,<NA>,False,1,<NA>,<NA>
1,0,2,989,NJ,LINCOLN TOWNCAR,,BK,1996,NJ,2,12,12,6,,0,4,<NA>,2,3,26,<NA>,<NA>,<NA>,0,False,1,<NA>,<NA>
2,1,1,962,NJ,TOYOTA 4DR,,GRN,1997,NJ,1,11,<NA>,1,,<NA>,25,<NA>,3,10,28,<NA>,<NA>,<NA>,<NA>,False,1,<NA>,<NA>
3,1,2,<NA>,,,,,0,,<NA>,0,0,5,,0,2,<NA>,1,1,26,<NA>,<NA>,<NA>,0,False,0,<NA>,<NA>
4,2,1,85,NJ,CHEVY CORSICA,,PUR,1996,NJ,3,8,15,1,,<NA>,25,<NA>,3,1,26,1,<NA>,<NA>,<NA>,False,6,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12375704,6567540,2,<NA>,PA,FORD,Transit,WT,2021,PA,2,11,11,3,02,3,25,<NA>,3,3,26,<NA>,<NA>,<NA>,2,False,3,4,26
12375705,6567541,1,<NA>,WA,RAM,ProMaster 3500,BL,2020,NJ,2,12,12,3,02,3,2,98,2,1,69,98,98,98,2,False,1,2,69
12375706,6567542,1,12,NJ,VOLKSWAGEN,Golf GTI,WT,2021,NJ,3,12,12,1,01,<NA>,1,25,3,16,8,6,52,98,<NA>,False,3,4,52
12375707,6567543,1,963,NJ,TOYOTA,Tundra,MN,2006,NJ,3,12,12,5,01,<NA>,4,98,1,3,26,19,98,98,<NA>,False,4,4,26
12375708,6567543,2,370,NJ,CHEVROLET,Impala,BK,2015,NJ,3,12,12,1,01,<NA>,25,98,3,1,26,98,98,98,<NA>,False,3,4,26

In [22]:
vm = v.merge(c, left_on='crash_id', right_index=True, how='left', validate='m:1')
vm['towed'] = vm.departure >= 3
vm['impounded'] = (vm.departure == 4) | (vm.departure == 5)
vm['driven'] = vm.departure == 1
vm['disabled'] = (vm.departure == 3) | (vm.departure == 5) | (vm.damage == 4)
vm['condition'] = vm.damage.fillna(0).astype(int)
vm['left'] = vm.departure == 2
vm.loc[vm.disabled, 'condition'] = 4
vm

,crash_id,vn,ins_co,owner_state,make,model,color,vy,state,rm_by,impact_loc,damage_loc,type,use,cargo_type,cir1,cir2,dir,act,ev1,ev2,ev3,ev4,oversize,hit_run,departure,damage,ev,y,m,cc,mc,severity,tk,ti,pk,pi,towed,impounded,driven,disabled,condition,left
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,0,1,426,NJ,NISSAN MAXIMA,,BUR,1991,NJ,<NA>,8,7,1,,<NA>,25,<NA>,1,3,26,<NA>,<NA>,<NA>,<NA>,False,1,<NA>,<NA>,2001,12,1,1.0,p,0,0,0,0,False,False,True,<NA>,0,False
1,0,2,989,NJ,LINCOLN TOWNCAR,,BK,1996,NJ,2,12,12,6,,0,4,<NA>,2,3,26,<NA>,<NA>,<NA>,0,False,1,<NA>,<NA>,2001,12,1,1.0,p,0,0,0,0,False,False,True,<NA>,0,False
2,1,1,962,NJ,TOYOTA 4DR,,GRN,1997,NJ,1,11,<NA>,1,,<NA>,25,<NA>,3,10,28,<NA>,<NA>,<NA>,<NA>,False,1,<NA>,<NA>,2001,1,1,1.0,p,0,0,0,0,False,False,True,<NA>,0,False
3,1,2,<NA>,,,,,0,,<NA>,0,0,5,,0,2,<NA>,1,1,26,<NA>,<NA>,<NA>,0,False,0,<NA>,<NA>,2001,1,1,1.0,p,0,0,0,0,False,False,False,<NA>,0,False
4,2,1,85,NJ,CHEVY CORSICA,,PUR,1996,NJ,3,8,15,1,,<NA>,25,<NA>,3,1,26,1,<NA>,<NA>,<NA>,False,6,<NA>,<NA>,2001,4,1,1.0,i,0,4,0,0,True,False,False,<NA>,0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12375704,6567540,2,<NA>,PA,FORD,Transit,WT,2021,PA,2,11,11,3,02,3,25,<NA>,3,3,26,<NA>,<NA>,<NA>,2,False,3,4,26,2023,12,21,23.0,p,0,0,0,0,True,False,False,True,4,False
12375705,6567541,1,<NA>,WA,RAM,ProMaster 3500,BL,2020,NJ,2,12,12,3,02,3,2,98,2,1,69,98,98,98,2,False,1,2,69,2023,12,21,23.0,p,0,0,0,0,False,False,True,False,2,False
12375706,6567542,1,12,NJ,VOLKSWAGEN,Golf GTI,WT,2021,NJ,3,12,12,1,01,<NA>,1,25,3,16,8,6,52,98,<NA>,False,3,4,52,2023,9,21,23.0,p,0,0,0,0,True,False,False,True,4,False
12375707,6567543,1,963,NJ,TOYOTA,Tundra,MN,2006,NJ,3,12,12,5,01,<NA>,4,98,1,3,26,19,98,98,<NA>,False,4,4,26,2023,12,21,23.0,i,0,1,0,0,True,True,False,True,4,False
12375708,6567543,2,370,NJ,CHEVROLET,Impala,BK,2015,NJ,3,12,12,1,01,<NA>,25,98,3,1,26,98,98,98,<NA>,False,3,4,26,2023,12,21,23.0,i,0,1,0,0,True,False,False,True,4,False

In [23]:
cmymv = vm.groupby(cmym_cols)[['hit_run', 'towed', 'disabled']].sum()
cmymv

                 hit_run  towed  disabled
cc mc   y    m
1  1.0  2001 1         0     14         0
             2         0     10         0
             3         0     22         0
             4         0     27         0
             5         0     10         0
...                  ...    ...       ...
21 23.0 2023 8         0      1         7
             9         1     12        13
             10        1      6         6
             11        1      7         7
             12        0      9         9

[143516 rows x 3 columns]

In [24]:
sql.write(
    cmymv, 'cmymv', CMYMC_DB,
    idxs=[cmym_cols],
    replace=False,
    # page_size=2**16,
)

Writing 143516 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cmymv)
Wrote DB: 55574528 bytes
After indices: 58064896 bytes

In [25]:
cmyv = sum_idx_col(cmymv, 'm', tbl_suffix='v')
cmyv

Writing 12729 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cmyv)
Wrote DB: 58982400 bytes
After indices: 59244544 bytes

              hit_run  towed  disabled
cc mc   y
1  1.0  2001        0    193         0
        2002        0    191         0
        2003        0    238         0
        2004        0    191         0
        2005        0    181         0
...               ...    ...       ...
21 23.0 2019        6     85        88
        2020        7     65        66
        2021        3     31        60
        2022        3      6        72
        2023        4     45        89

[12729 rows x 3 columns]

In [26]:
cymv = sum_idx_col(cmymv, 'mc', tbl_suffix='v')
cymv

Writing 5784 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cymv)
Wrote DB: 59637760 bytes
After indices: 59834368 bytes

            hit_run  towed  disabled
cc y    m
1  2001 1         0    343         0
        2         0    419         0
        3         0    314         0
        4         0    332         0
        5         0    350         0
...             ...    ...       ...
21 2023 8         6     34        98
        9        17    103       108
        10       13    130       132
        11       20    115       116
        12       16    110       112

[5784 rows x 3 columns]

In [27]:
cyv = sum_idx_col(cymv, 'm', tbl_suffix='v')
cyv

Writing 482 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (cyv)
Wrote DB: 60030976 bytes
After indices: 60096512 bytes

         hit_run  towed  disabled
cc y
1  2001        0   4442         0
   2002        0   4795         0
   2003        0   5125         0
   2004        0   5476         0
   2005        0   5272         0
...          ...    ...       ...
21 2019      270   1880      1936
   2020      215   1422      1467
   2021      202   1265      1615
   2022      119    611      1243
   2023      109    798      1178

[482 rows x 3 columns]

In [28]:
ymv = sum_idx_col(cymv, 'cc', tbl_suffix='v')
ymv

Writing 276 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (ymv)
Wrote DB: 60293120 bytes
After indices: 60358656 bytes

         hit_run  towed  disabled
y    m
2001 1         0  11579         0
     2         0   9624         0
     3         0   9770         0
     4         0   9166         0
     5         0  10659         0
...          ...    ...       ...
2023 8      2275   6365      7731
     9      2475   7385      8393
     10     2519   8113      8758
     11     2676   8513      9082
     12     2799   8882      9432

[276 rows x 3 columns]

In [29]:
yv = sum_idx_col(ymv, 'm', tbl_suffix='v', page_size=2**16)
yv

Writing 23 rows to /Users/ryan/c/hccs/crashes/www/public/njdot/cmymc.db (yv)
Wrote DB: 60489728 bytes
After indices: 60555264 bytes
After setting page_size=65536 and vacuum: 59834368 bytes

      hit_run   towed  disabled
y
2001        0  129096         0
2002        0  136971         0
2003        0  139858         0
2004        0  141870         0
2005        0  138166         0
2006    39032  126134         0
2007    41291  128322         0
2008    40903  123938         0
2009    39749  122630         0
2010    39654  120327         0
2011    38673  116793         0
2012    36415  115394         0
2013    36942  116586         0
2014    37485  113974         0
2015    32668  116859         0
2016    33874  121459         0
2017    33624  121449    129716
2018    34325  124425    132189
2019    35334  120866    129221
2020    27712   93303    100024
2021    31396   96434    112571
2022    30575   90919    117143
2023    28094   81552     96057

In [30]:
import boto3
s3 = boto3.client('s3')

In [31]:
s3.upload_file(CMYMC_DB, Bucket='nj-crashes', Key=f'njdot/data/{basename(CMYMC_DB)}')